// layout.tsx
// Imports
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/ui/navbar";
import Footer from "./components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          `grid grid-rows-[auto_1fr_auto] min-h-screen dark:bg-gray-800
          ${geistSans.variable} 
          ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main id="content" className="mx-4 sm:mx-8 w-5/6 sm:w-2/3 justify-self-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
